=== bioperl/bioperl-pedigree/resources/pedigree.dtd
<!-- BioXML Pedigree DTD 
     Version:  0.02
     Revision: $Id$
     Author List:
        Primary Author: Jason Stajich (Duke University) 
     ================================================================ 
-->

<!ELEMENT PEDIGREE (MARKER*,GROUP+)>
<!ATTLIST PEDIGREE 
  date    CDATA
  comment CDATA
>

<!ELEMENT GROUP (PERSON*)>
<!ATTLIST GROUP
   center CDATA #REQUIRED
   id     CDATA #REQUIRED
   type   CDATA #IMPLIED
   description CDATA #IMPLIED>

<!ELEMENT PERSON (RESULT*)>
<!ATTLIST PERSON 
  id          CDATA #REQUIRED
  father      CDATA  #REQUIRED
  mother      CDATA  #REQUIRED
  gender      CDATA  ( M | F | U) 'U'
  displayid   CDATA
  child       CDATA #IMPLIED
  paternalsib CDATA #IMPLIED
  maternalsib CDATA #IMPLIED
>

<!ELEMENT RESULT (ALLELE+)>
<!ATTLIST RESULT marker CDATA #REQUIRED>
<!ELEMENT ALLELE (#PCDATA)> 

<!ELEMENT MARKER (LIAB_CLASSES*,FREQUENCY*,UPSTREAMSEQ?,
                  DNSTREAMSEQ?,MARKER_ALLELE*,)>

<!ATTLIST MARKER 
  name         CDATA #REQUIRED
  type         CDATA #REQUIRED  
  description  CDATA
  display_name CDATA
  result_allele_count CDATA #IMPLIED
  chrom        CDATA --only present in mapped variations
>

<!ELEMENT FREQUENCY>
<!ATTLIST FREQUENCY 
  aff_freq   CDATA #REQUIRED
  unaff_freq CDATA #REQUIRED
>

<!ELEMENT LIAB_CLASSES (PENETRANCE*)>
<!ATTLIST LIAB_CLASSES class CDATA #REQUIRED>
<!ELEMENT PENETRANCE>
<!ATTLIST PENETRANCE 
  dom     CDATA #REQUIRED --Homozygous Dominant
  het     CDATA #REQUIRED --Heterozygous
  rec     CDATA #REQUIRED --Homozygous Reccessive
>

<!ELEMENT MARKER_ALLELE>
<!ATTLIST MARKER_ALLELE 
  allele  CDATA #REQUIRED
  frequency CDATA #REQUIRED
>
 
<!ELEMENT UPSTREAMSEQ (#PCDATA)>
<!ELEMENT DNSTREAMSEQ (#PCDATA)>

=== bioperl/bioperl-pedigree/resources/pedigree_example.xml
<!DOCTYPE PEDIGREE SYSTEM "pedigree.dtd">
<PEDIGREE date="2001-06-19" comment="example pedigree">
   <MARKER name="ALZAFF" type="disease" display_name="ALZAFF"
           description="disease mkr ex" result_allele_count="1">
      <LIAB_CLASS name="N10">
         <PENETRANCE dom="0.0000" het="0.0000" rec="1.000" />
      </LIAB_CLASS>
      <LIAB_CLASS name="N20">
         <PENETRANCE dom="0.0000" het="0.0000" rec="1.000" />
      </LIAB_CLASS>
      <LIAB_CLASS name="N30">
         <PENETRANCE dom="0.0000" het="0.0000" rec="1.000" />
      </LIAB_CLASS>
      <LIAB_CLASS name="A">
         <PENETRANCE dom="1.0000" het="0.0000" rec="0.000" />
      </LIAB_CLASS>   
   </MARKER>
   <MARKER name="D1S123" type="variation" display_name="D1S123"
           description="variation mkr ex" result_allele_count="2"
	   chrom="1">
      <UPSTREAMSEQ>AAAACCCCTTT</UPSTREAMSEQ>
      <DNSTREAMSEQ>TGATTCATGG</DNSTREAMSEQ>
      <MARKER_ALLELE allele="100" frequency="0.100" />
      <MARKER_ALLELE allele="105" frequency="0.400" />
      <MARKER_ALLELE allele="109" frequency="0.250" />
      <MARKER_ALLELE allele="110" frequency="0.250" />
   </MARKER>

   <GROUP id="101" center="XXX" type="FAMILY" 
          description="example family">
      <PERSON id="1" displayid="2000" father="0" mother="0"
              gender="M">
         <RESULT marker="D1S123">
	    <ALLELE>100</ALLELE>
	    <ALLELE>105</ALLELE>
	 </RESULT>
	 <RESULT marker="ADAFF">
	    <ALLELE>U</ALLELE>
	 </RESULT>
      </PERSON>
      <PERSON id="1" displayid="2000" father="0" mother="0"
              gender="M">
         <RESULT marker="D1S123">
	    <ALLELE>100</ALLELE>
	    <ALLELE>105</ALLELE>
	 </RESULT>
	 <RESULT marker="ADAFF">
	    <ALLELE>U</ALLELE>
	 </RESULT>
      </PERSON>
      <PERSON id="2" displayid="2001" father="0" mother="0"
              gender="F">
	 <RESULT marker="ADAFF">
	    <ALLELE>U</ALLELE>
	 </RESULT>
      </PERSON>
      <PERSON id="3" displayid="1000" father="1" mother="2"
              gender="F">
         <RESULT marker="D1S123">
	    <ALLELE>105</ALLELE>
	    <ALLELE>109</ALLELE>
	 </RESULT>
	 <RESULT marker="ADAFF">
	    <ALLELE>U</ALLELE>
	 </RESULT>
      </PERSON>
      <PERSON id="4" displayid="1001" father="0" mother="0"
              gender="M">
         <RESULT marker="D1S123">
	    <ALLELE>110</ALLELE>
	    <ALLELE>100</ALLELE>
	 </RESULT>
	 <RESULT marker="ADAFF">
	    <ALLELE>U</ALLELE>
	 </RESULT>
      </PERSON>
      <PERSON id="5" displayid="0001" father="4" mother="3"
              gender="F">
         <RESULT marker="D1S123">
	    <ALLELE>110</ALLELE>
	    <ALLELE>109</ALLELE>
	 </RESULT>
	 <RESULT marker="ADAFF">
	    <ALLELE>A</ALLELE>
	 </RESULT>
      </PERSON>
   </GROUP>
</PEDIGREE>
